global:
    imageRegistry: registry.inner.silinex.work/silinex-maas
image:
    nfs:
        repository: nfsplugin
        tag: v4.13.2
        pullPolicy: IfNotPresent
    csiProvisioner:
        repository: csi-provisioner
        tag: v6.1.0
        pullPolicy: IfNotPresent
    csiResizer:
        repository: csi-resizer
        tag: v2.0.0
        pullPolicy: IfNotPresent
    csiSnapshotter:
        repository: csi-snapshotter
        tag: v8.4.0
        pullPolicy: IfNotPresent
    livenessProbe:
        repository: livenessprobe
        tag: v2.17.0
        pullPolicy: IfNotPresent
    nodeDriverRegistrar:
        repository: csi-node-driver-registrar
        tag: v2.15.0
        pullPolicy: IfNotPresent
    externalSnapshotter:
        repository: snapshot-controller
        tag: v8.4.0
        pullPolicy: IfNotPresent

imagePullSecrets:
  - name: registry-secret
