{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "silinex-maas-frontend.secretName" . }}
  labels:
    {{- include "silinex-maas-frontend.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | toString | quote }}
  LOGTO_APP_SECRET: {{ .Values.secrets.LOGTO_APP_SECRET | toString | quote }}
  LOGTO_COOKIE_SECRET: {{ .Values.secrets.LOGTO_COOKIE_SECRET | toString | quote }}
  {{- range $name, $value := .Values.secrets.extraStringData }}
  {{ $name }}: {{ $value | toString | quote }}
  {{- end }}
{{- end }}
