apiVersion: v1
kind: Service
metadata:
  name: {{ include "silinex-maas-frontend.fullname" . }}
  labels:
    {{- include "silinex-maas-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "silinex-maas-frontend.selectorLabels" . | nindent 4 }}
