apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logto.fullname" . }}
  labels:
    {{- include "logto.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "logto.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "logto.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "logto.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.logto.command | nindent 12 }}
          args:
            {{- toYaml .Values.logto.args | nindent 12 }}
          ports:
            - name: app
              containerPort: {{ .Values.service.ports.app }}
              protocol: TCP
            - name: admin
              containerPort: {{ .Values.service.ports.admin }}
              protocol: TCP
          env:
            - name: TRUST_PROXY_HEADER
              value: {{ .Values.logto.trustProxyHeader | quote }}
            - name: PORT
              value: {{ .Values.service.ports.app | quote }}
            - name: ADMIN_PORT
              value: {{ .Values.service.ports.admin | quote }}
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: {{ .Values.logto.nodeTlsRejectUnauthorized | quote }}
            - name: ENDPOINT
              value: {{ .Values.logto.endpoint | quote }}
            - name: ADMIN_ENDPOINT
              value: {{ .Values.logto.adminEndpoint | quote }}
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "logto.secretName" . }}
                  key: {{ .Values.existingSecret.dbUrlKey | default "DB_URL" }}
            {{- with .Values.logto.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
