apiVersion: v1
kind: Service
metadata:
  name: {{ include "logto.fullname" . }}
  labels:
    {{- include "logto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: app
      port: {{ .Values.service.ports.app }}
      targetPort: app
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.app }}
      nodePort: {{ .Values.service.nodePorts.app }}
      {{- end }}
    - name: admin
      port: {{ .Values.service.ports.admin }}
      targetPort: admin
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.admin }}
      nodePort: {{ .Values.service.nodePorts.admin }}
      {{- end }}
  selector:
    {{- include "logto.selectorLabels" . | nindent 4 }}
