{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "silinex-maas-server.secretName" . }}
  labels:
    {{- include "silinex-maas-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  SILINEX_ENV: {{ .Values.config.env | toString | quote }}
  SILINEX_SERVER_HOST: {{ .Values.config.serverHost | toString | quote }}
  SILINEX_SERVER_PORT: {{ .Values.config.serverPort | toString | quote }}
  SILINEX_SERVER_SESSION_SECRET: {{ .Values.secrets.serverSessionSecret | toString | quote }}
  SILINEX_JWT_KEY: {{ .Values.secrets.jwtKey | toString | quote }}
  SILINEX_JWT_MAX_AGE: {{ .Values.config.jwtMaxAge | toString | quote }}
  SILINEX_DB_DSN: {{ include "silinex-maas-server.serverDsn" . | quote }}
  SILINEX_REDIS_MODE: {{ .Values.redis.mode | toString | quote }}
  SILINEX_REDIS_ADDR: {{ .Values.redis.addr | toString | quote }}
  SILINEX_REDIS_USERNAME: {{ .Values.redis.username | toString | quote }}
  SILINEX_REDIS_PASSWORD: {{ .Values.redis.password | toString | quote }}
  SILINEX_REDIS_DB: {{ .Values.redis.db | toString | quote }}
  SILINEX_REDIS_SENTINEL_ADDRS: {{ include "silinex-maas-server.redisSentinelAddrs" . | quote }}
  SILINEX_REDIS_SENTINEL_MASTER_NAME: {{ .Values.redis.sentinelMasterName | toString | quote }}
  SILINEX_REDIS_SENTINEL_USERNAME: {{ .Values.redis.sentinelUsername | toString | quote }}
  SILINEX_REDIS_SENTINEL_PASSWORD: {{ .Values.redis.sentinelPassword | toString | quote }}
  SILINEX_LOGTO_MANAGEMENT_ENDPOINT: {{ .Values.logto.managementEndpoint | toString | quote }}
  SILINEX_LOGTO_MANAGEMENT_APP_ID: {{ .Values.logto.managementAppId | toString | quote }}
  SILINEX_LOGTO_MANAGEMENT_APP_SECRET: {{ .Values.logto.managementAppSecret | toString | quote }}
  SILINEX_LOGTO_MANAGEMENT_DATABASE: {{ include "silinex-maas-server.logtoManagementDsn" . | quote }}
  SILINEX_SERVER_SELF_HOST: {{ include "silinex-maas-server.selfHost" . | quote }}
  SILINEX_ENABLE_SCHEDULER: {{ .Values.config.enableScheduler | toString | quote }}
  DEBUG_ENABLE_FAKE_LOGIN: {{ .Values.config.debugEnableFakeLogin | toString | quote }}
  ENABLE_PRETTY_CONSOLE: {{ .Values.config.enablePrettyConsole | toString | quote }}
  SILINEX_APP_JWT_SECRET: {{ .Values.secrets.appJwtSecret | toString | quote }}
  SILINEX_APP_JWT_COOKIES_NAME: {{ .Values.secrets.appJwtCookiesName | toString | quote }}
  SILINEX_ADMIN_JWT_SECRET: {{ .Values.secrets.adminJwtSecret | toString | quote }}
  SILINEX_ADMIN_JWT_COOKIES_NAME: {{ .Values.secrets.adminJwtCookiesName | toString | quote }}
  SILINEX_MODEL_MANAGER_ENDPOINT: {{ .Values.config.modelManagerEndpoint | toString | quote }}
  SILINEX_MODEL_MANAGER_DEFAULT_ORG_ID: {{ .Values.config.modelManagerDefaultOrgId | toString | quote }}
  SILINEX_SHARE_DATA_PV_NAME: {{ .Values.config.shareDataPVName | toString | quote }}
  SILINEX_SHARE_DATA_STORAGE_CLASS_NAME: {{ .Values.config.shareDataStorageClassName | toString | quote }}
  SILINEX_SHARE_DATA_MOUNT_PATH: {{ .Values.config.shareDataMountPath | toString | quote }}
  SILINEX_SHARE_DATA_NFS_SERVER: {{ .Values.config.shareDataNfsServer | toString | quote }}
  SILINEX_SHARE_DATA_NFS_SHARE: {{ .Values.config.shareDataNfsShare | toString | quote }}
  SILINEX_VOLUME_MODEL_HOSTPATH: {{ .Values.config.volumeModelHostPath | toString | quote }}
  SILINEX_SHARE_DATA_MOUNT_PAT: {{ .Values.config.shareDataMountPat | toString | quote }}
  SILINEX_PROMETHEUS_ENDPOINT: {{ .Values.config.prometheusEndpoint | toString | quote }}
  SILINEX_K8S_RESOURCE_NAME_TEMPLATE_SUFFIX: {{ .Values.config.k8sResourceNameTemplateSuffix | toString | quote }}
  SILINEX_POC_TEMP: {{ .Values.config.pocTemp | toString | quote }}
  SILINEX_ADMIN_ORG_ID: {{ .Values.config.adminOrgId | toString | quote }}
  SILINEX_APP_NORMAL_USER_ROLE_IDS: {{ .Values.config.appNormalUserRoleIds | toString | quote }}
  SILINEX_APP_MANAGER_USER_ROLE_IDS: {{ .Values.config.appManagerUserRoleIds | toString | quote }}
  SILINEX_ADMIN_USER_ROLE_IDS: {{ .Values.config.adminUserRoleIds | toString | quote }}
  FOO: {{ .Values.config.foo | toString | quote }}
  {{- range $name, $value := .Values.config.extraEnv }}
  {{ $name }}: {{ $value | toString | quote }}
  {{- end }}
  {{- range $name, $value := .Values.secrets.extraStringData }}
  {{ $name }}: {{ $value | toString | quote }}
  {{- end }}
{{- end }}
