apiVersion: v1
kind: Secret
metadata:
  name: pg-user-password
  namespace: sf-maas
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: "silinex"
  password: "silicon@123"
