global:
  imageRegistry: registry.inner.silinex.work/silinex-maas

image:
  repository: silinex-maas-server
  tag: "amd64-2253a55d-20260427-0136"
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}
  name: ""

podSecurityContext: {}
securityContext: {}
nodeSelector:
  kubernetes.io/arch: amd64
  kubernetes.io/hostname: dev-vm-120
tolerations: []
affinity: {}
hostAliases: []

postgres:
  host: pg-prod-rw
  port: 5432
  user: silinex
  password: silicon@123
  sslmode: disable
  timezone: Asia/Shanghai
  serverDatabase: silinex_maas_test
  logtoDatabase: maas_idp_test
  serverDsnOverride: ""
  logtoManagementDsnOverride: ""

redis:
  mode: sentinel
  addr: redis-cache:6379
  username: ""
  password: silicon@123
  db: 1
  sentinelAddrs:
    - redis-cache:26379
  sentinelMasterName: "redis-cache-master"
  sentinelUsername: ""
  sentinelPassword: ""

logto:
  managementEndpoint: http://logto:16001
  managementAppId: m9simpbev42ipoijac8hl
  managementAppSecret: 6nteZElWEGF44mbc4XGZBsHEvJdBTd0n

config:
  env: dev
  serverHost: 0.0.0.0
  serverPort: 16100
  serverSelfHost: https://maas.gz.xxxxxxxx.com
  jwtMaxAge: "360000"
  enableScheduler: true
  debugEnableFakeLogin: false
  enablePrettyConsole: true
  modelManagerEndpoint: http://silinex-model-downloader:16102
  modelManagerDefaultOrgId: silinex
  shareDataPVName: pv-nfs
  shareDataStorageClassName: nfs-csi
  shareDataMountPath: /data/models
  shareDataNfsServer: 10.191.59.2
  shareDataNfsShare: /data-models
  volumeModelHostPath: /maasjfs
  shareDataMountPat: /data/models
  prometheusEndpoint: http://prometheus:9090
  k8sResourceNameTemplateSuffix: ""
  pocTemp: false
  adminOrgId: "1"
  appNormalUserRoleIds: "2,3"
  appManagerUserRoleIds: "1"
  adminUserRoleIds: "4"
  foo: BAR
  extraEnv: {}

secrets:
  create: true
  name: ""
  existingSecret: ""
  serverSessionSecret: asaddjhk12g309123jkabasdkjghsd
  jwtKey: as13kjhgscv!@sxoiuy
  appJwtSecret: 72bc230132092e40d478adbbba8db1996ce47159f7ed05810097250306814764e9298ec2b8406ce71a71f3a5636db83e563113d4ec8ac0e5c3bd35e793486fe9
  appJwtCookiesName: silinex-maas
  adminJwtSecret: 72bc230132092e40d478adbbba8db1996ce47159f7ed05810097250306814764e9298ec2b8406ce71a71f3a5636db83e563113d4ec8ac0e5c3bd35e793486fe9
  adminJwtCookiesName: silinex-maas
  extraStringData: {}

initJob:
  enabled: true
  name: silinex-maas-server-init
  annotations: {}
  labels: {}
  podAnnotations: {}
  podLabels: {}
  command: []
  argsOverride: []
  adminUsername: maasadmin
  adminPassword: 2g8A64kBY5E5xR
  autoMigrate: true
  restartPolicy: Never
  backoffLimit: 6
  ttlSecondsAfterFinished: null
  extraEnv: []
  resources: {}

server:
  enabled: true
  name: silinex-maas-server
  replicaCount: 1
  annotations: {}
  podAnnotations: {}
  podLabels: {}
  command: []
  args:
    - -mode
    - server
  extraEnv: []
  service:
    type: ClusterIP
    port: 16100
  livenessProbe:
    enabled: true
    tcpSocket:
      port: http
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 6
  readinessProbe:
    enabled: true
    tcpSocket:
      port: http
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  resources: {}
