apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "silinex-maas-docs.fullname" . }}
  labels:
    {{- include "silinex-maas-docs.labels" . | nindent 4 }}
data:
  {{- range $name, $value := .Values.config }}
  {{- if ne $name "extraEnv" }}
  {{ $name }}: {{ $value | toString | quote }}
  {{- end }}
  {{- end }}
  {{- range $name, $value := .Values.config.extraEnv }}
  {{ $name }}: {{ $value | toString | quote }}
  {{- end }}
