apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "silinex-model-downloader.fullname" . }}
  labels:
    {{- include "silinex-model-downloader.labels" . | nindent 4 }}
data:
  SILINEX_DATABASE_NAME: {{ .Values.database.name | toString | quote }}
  SILINEX_MODEL_BASE_PATH: {{ .Values.model.basePath | toString | quote }}
  {{- range $name, $value := .Values.config.extraEnv }}
  {{ $name }}: {{ $value | toString | quote }}
  {{- end }}
