{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "silinex-model-downloader.secretName" . }}
  labels:
    {{- include "silinex-model-downloader.labels" . | nindent 4 }}
type: Opaque
stringData:
  SILINEX_DATABASE_URL: {{ .Values.database.url | toString | quote }}
  SILINEX_MODELSCOPE_AUTH_TOKEN: {{ .Values.authTokens.modelScope | toString | quote }}
  SILINEX_HUGGINGFACE_AUTH_TOKEN: {{ .Values.authTokens.huggingFace | toString | quote }}
  {{- range $name, $value := .Values.secrets.extraStringData }}
  {{ $name }}: {{ $value | toString | quote }}
  {{- end }}
{{- end }}
